import Quick
import Nimble
import AppKit
@testable import Thoth

/// クリップボード秘匿（org.nspasteboard.ConcealedType）対応のスペック。
/// セキュアメニューの出力が Clipy 自身の履歴（および対応する他のクリップボード
/// マネージャー）に保存されないことを担保する。
///
/// 注意: 実ペーストボード（NSPasteboard.general）を使うテストを含むため、
/// 直列実行を前提とし afterEach で必ずクリアする。
class ClipboardConcealSpec: QuickSpec {
    override class func spec() {

        // MARK: - 履歴除外の判定ロジック（純関数）

        describe("shouldExcludeFromHistory") {

            it("Excludes concealed type") {
                let types: [NSPasteboard.PasteboardType] = [.string, Constants.Pasteboard.concealedType]
                expect(ClipService.shouldExcludeFromHistory(types: types)) == true
            }

            it("Excludes transient type") {
                let types: [NSPasteboard.PasteboardType] = [.string, Constants.Pasteboard.transientType]
                expect(ClipService.shouldExcludeFromHistory(types: types)) == true
            }

            it("Excludes auto-generated type") {
                let types: [NSPasteboard.PasteboardType] = [Constants.Pasteboard.autoGeneratedType]
                expect(ClipService.shouldExcludeFromHistory(types: types)) == true
            }

            it("Does not exclude ordinary copies") {
                let types: [NSPasteboard.PasteboardType] = [.string, .rtf, .tiff]
                expect(ClipService.shouldExcludeFromHistory(types: types)) == false
            }

            it("Does not exclude an empty type list") {
                expect(ClipService.shouldExcludeFromHistory(types: [])) == false
            }
        }

        // MARK: - 秘匿コピー（実ペーストボード使用）

        describe("copyConcealedToPasteboard") {
            afterEach {
                NSPasteboard.general.clearContents()
            }

            it("Writes the string together with concealed and transient markers") {
                let service = PasteService()
                service.copyConcealedToPasteboard(with: "s3cr3t-value")

                let pasteboard = NSPasteboard.general
                let types = pasteboard.types ?? []
                expect(types).to(contain(Constants.Pasteboard.concealedType))
                expect(types).to(contain(Constants.Pasteboard.transientType))
                expect(pasteboard.string(forType: .deprecatedString)) == "s3cr3t-value"
                // 書き込んだ内容が履歴除外判定に引っかかることを end-to-end で確認
                expect(ClipService.shouldExcludeFromHistory(types: types)) == true
            }

            it("Ordinary copy does not carry the concealed marker") {
                let service = PasteService()
                service.copyToPasteboard(with: "ordinary")

                let types = NSPasteboard.general.types ?? []
                expect(types).toNot(contain(Constants.Pasteboard.concealedType))
                expect(ClipService.shouldExcludeFromHistory(types: types)) == false
            }
        }

        // MARK: - 条件付き遅延クリア

        describe("scheduleConcealedClear") {
            afterEach {
                NSPasteboard.general.clearContents()
            }

            it("Clears the pasteboard after the delay when nothing else was copied") {
                let service = PasteService()
                service.copyConcealedToPasteboard(with: "to-be-cleared")
                service.scheduleConcealedClear(after: 0.2)

                expect(NSPasteboard.general.string(forType: .deprecatedString))
                    .toEventually(beNil(), timeout: .seconds(3), pollInterval: .milliseconds(50))
            }

            it("Keeps the pasteboard when the user copied something else in the meantime") {
                let service = PasteService()
                service.copyConcealedToPasteboard(with: "secret")
                service.scheduleConcealedClear(after: 0.2)
                // ユーザーが別の内容をコピーした（changeCount が進む）
                service.copyToPasteboard(with: "user-copy")

                // 遅延クリアが発火しても user-copy は消えない
                waitUntil(timeout: .seconds(3)) { done in
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { done() }
                }
                expect(NSPasteboard.general.string(forType: .deprecatedString)) == "user-copy"
            }
        }
    }
}
