//
//  ClipService.swift
//
//  Clipy
//  GitHub: https://github.com/clipy
//  HP: https://clipy-app.com
//
//  Created by Econa77 on 2016/11/17.
//
//  Copyright © 2015-2018 Clipy Project.
//

import Foundation
import Cocoa
import PINCache
import RxSwift
import RxCocoa

/// クリップボードの監視と履歴の保存・削除を担うサービス。
///
/// ## 監視方式
/// NSPasteboard には変更通知 API が無いため、changeCount を 100ms 間隔で
/// ポーリングして変化を検出する（.utility QoS の直列スケジューラ上）。
///
/// ## 保存の流れ
/// changeCount 変化 → create()（除外判定・型フィルタ）→ save()：
/// 重複判定・サムネイル生成・NSKeyedArchiver シリアライズ・ファイル書き込み・
/// 保存層（HistoryStore）への追加のすべてを専用直列キュー（saveQueue）で行い、メインスレッドを塞がない。
/// クリップ本体（.data）は ClipDataStore が AES-GCM で暗号化して保存する。
///
/// ## 履歴に保存しないもの
/// - 秘匿マーカー（org.nspasteboard.ConcealedType 等）付きのコピー
/// - 除外アプリが最前面のときのコピー
/// - 保存対象外の型のみのコピー・空文字列
final class ClipService {

    // MARK: - Properties
    fileprivate var cachedChangeCount = BehaviorRelay<Int>(value: 0)
    fileprivate var storeTypes = [String: NSNumber]()
    // changeCount の読み取りは極めて軽量なため、常駐ポーリングは .utility で十分
    // （体感遅延は最大でもポーリング間隔の 100ms のまま）
    fileprivate let scheduler = SerialDispatchQueueScheduler(qos: .utility)
    fileprivate let lock = NSRecursiveLock(name: "io.github.boyaki-machine.Thoth.ClipUpdatable")
    fileprivate var disposeBag = DisposeBag()
    // アーカイブ・サムネイル生成・ファイル書き込みをメインスレッドから逃すための直列キュー
    fileprivate let saveQueue = DispatchQueue(label: "io.github.boyaki-machine.Thoth.ClipSave", qos: .userInitiated)

    // MARK: - Clips
    /// クリップボードのポーリング監視と保存対象型の設定監視を開始する
    func startMonitoring() {
        disposeBag = DisposeBag()
        // Pasteboard observe timer
        Observable<Int>.interval(.milliseconds(100), scheduler: scheduler)
            .map { _ in NSPasteboard.general.changeCount }
            .withLatestFrom(cachedChangeCount.asObservable()) { ($0, $1) }
            .filter { $0 != $1 }
            .subscribe(onNext: { [weak self] changeCount, _ in
                self?.cachedChangeCount.accept(changeCount)
                self?.create()
            })
            .disposed(by: disposeBag)
        // Store types
        AppEnvironment.current.defaults.rx
            .observe([String: NSNumber].self, Constants.UserDefaults.storeTypes)
            .compactMap { $0 }
            .asDriver(onErrorDriveWith: .empty())
            .drive(onNext: { [weak self] in
                self?.storeTypes = $0
            })
            .disposed(by: disposeBag)
    }

    /// 全履歴を削除する（サムネイルキャッシュ・.data ファイル含む）
    func clearAll() {
        let removed = AppEnvironment.current.historyStore.deleteAllClips()
        // Delete saved images
        removed
            .compactMap { $0.thumbnailPath.isEmpty ? nil : $0.thumbnailPath }
            .forEach { PINCache.shared.removeObject(forKey: $0) }
        // Delete writed datas
        AppEnvironment.current.dataCleanService.cleanDatas()
    }

    /// 指定クリップを履歴から削除する
    func delete(clipID: String) {
        guard let removed = AppEnvironment.current.historyStore.deleteClip(id: clipID) else { return }
        // Delete saved images
        if !removed.thumbnailPath.isEmpty {
            PINCache.shared.removeObject(forKey: removed.thumbnailPath)
        }
    }

    /// キャッシュ済み changeCount を進めて「次のクリップボード変化を 1 回無視」する。
    /// 自分自身の書き込みを履歴に再取り込みしないためのフック
    func incrementChangeCount() {
        cachedChangeCount.accept(cachedChangeCount.value + 1)
    }

}

// MARK: - Create Clip
extension ClipService {
    /// 秘匿・一時・自動生成マーカー（nspasteboard.org 規約）を含むコピーは
    /// 履歴に保存してはならない。Clipy 自身のセキュアメニュー出力や、
    /// 他のパスワードマネージャーからのコピーがこれに該当する。
    static func shouldExcludeFromHistory(types: [NSPasteboard.PasteboardType]) -> Bool {
        let excludedTypes: Set<NSPasteboard.PasteboardType> = [Constants.Pasteboard.concealedType,
                                                               Constants.Pasteboard.transientType,
                                                               Constants.Pasteboard.autoGeneratedType]
        return types.contains { excludedTypes.contains($0) }
    }

    fileprivate func create() {
        lock.lock(); defer { lock.unlock() }

        // Store types
        if !storeTypes.values.contains(NSNumber(value: true)) { return }
        // Pasteboard types
        let pasteboard = NSPasteboard.general
        // 秘匿マーカー付きのコピーは履歴に残さない
        if Self.shouldExcludeFromHistory(types: pasteboard.types ?? []) { return }
        let types = self.types(with: pasteboard)
        if types.isEmpty { return }

        // Excluded application
        guard !AppEnvironment.current.excludeAppService.frontProcessIsExcludedApplication() else { return }
        // Special applications
        guard !AppEnvironment.current.excludeAppService.copiedProcessIsExcludedApplications(pasteboard: pasteboard) else { return }

        // Create data
        let data = CPYClipData(pasteboard: pasteboard, types: types)
        save(with: data)
    }

    func create(with image: NSImage) {
        lock.lock(); defer { lock.unlock() }

        // Create only image data
        let data = CPYClipData(image: image)
        save(with: data)
    }

    fileprivate func save(with data: CPYClipData) {
        // 重複判定からアーカイブ生成・ファイル書き込みまでを専用の直列キューに
        // まとめて逃がし、ポーリングスレッドを重い処理でブロックしない
        saveQueue.async {
            let historyStore = AppEnvironment.current.historyStore
            // 画像クリップの場合 hash 計算に TIFF エンコードを伴うため一度だけ計算する
            let dataHash = data.hash
            // Copy already copied history
            let isCopySameHistory = AppEnvironment.current.defaults.bool(forKey: Constants.UserDefaults.copySameHistory)
            if historyStore.clip(id: historyStore.clipID(forContentHash: "\(dataHash)")) != nil, !isCopySameHistory { return }

            // Don't save empty string history
            if data.isOnlyStringType && data.stringValue.isEmpty { return }

            // Overwrite same history
            let isOverwriteHistory = AppEnvironment.current.defaults.bool(forKey: Constants.UserDefaults.overwriteSameHistory)
            let savedHash = isOverwriteHistory ? dataHash : Int.random(in: 0...999_999)

            // Saved time and path
            let unixTime = Int(Date().timeIntervalSince1970)
            let savedPath = CPYUtilities.applicationSupportFolder() + "/\(NSUUID().uuidString).data"
            var clip = ClipRecord(id: historyStore.clipID(forContentHash: "\(savedHash)"),
                                  dataPath: savedPath,
                                  title: data.stringValue[0...10000],
                                  primaryType: data.primaryType?.rawValue ?? "",
                                  updateTime: unixTime,
                                  thumbnailPath: "",
                                  isColorCode: false)

            // Save thumbnail image
            if let thumbnailImage = data.thumbnailImage {
                PINCache.shared.setObjectAsync(thumbnailImage, forKey: "\(unixTime)", completion: nil)
                clip.thumbnailPath = "\(unixTime)"
            }
            if let colorCodeImage = data.colorCodeImage {
                PINCache.shared.setObjectAsync(colorCodeImage, forKey: "\(unixTime)", completion: nil)
                clip.thumbnailPath = "\(unixTime)"
                clip.isColorCode = true
            }
            // Save history and .data file（.data は ClipDataStore が AES-GCM で暗号化する）
            if CPYUtilities.prepareSaveToPath(CPYUtilities.applicationSupportFolder()) {
                let archiveData = try? NSKeyedArchiver.archivedData(withRootObject: data, requiringSecureCoding: false)
                let archived = archiveData.map { ClipDataStore.shared.write($0, toPath: savedPath) } ?? false
                if archived {
                    historyStore.upsert(clip)
                }
            }
        }
    }

    private func types(with pasteboard: NSPasteboard) -> [NSPasteboard.PasteboardType] {
        let types = pasteboard.types?.filter { canSave(with: $0) } ?? []
        return NSOrderedSet(array: types).array as? [NSPasteboard.PasteboardType] ?? []
    }

    private func canSave(with type: NSPasteboard.PasteboardType) -> Bool {
        let dictionary = CPYClipData.availableTypesDictinary
        guard let value = dictionary[type] else { return false }
        guard let number = storeTypes[value] else { return false }
        return number.boolValue
    }
}
